# AppVeyor for Pyslvs-PyQt5
image: Visual Studio 2017

platform:
    - x64

environment:
    matrix:

        - MINGW_DIR: &mingw C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0
          MSYS_DIR: &msys2 C:\msys64
          PYTHON_DIR: C:\Python36-x64

        - MINGW_DIR: *mingw
          MSYS_DIR: *msys2
          PYTHON_DIR: C:\Python37-x64

skip_tags: true

install:
    # Environment variables.
    - set Path=%PYTHON_DIR%;%Path%
    - set Path=%PYTHON_DIR%\Scripts;%Path%
    - set Path=%MSYS_DIR%\usr\bin;%Path%
    - set Path=%MINGW_DIR%\mingw64\bin;%Path%

    # Show Python.
    - python --version
    - pip --version

    # Set Python compiler to Msys2.
    - pip install setuptools -U
    - echo [build]>> %PYTHON_DIR%\Lib\distutils\distutils.cfg
    - echo compiler = mingw32>> %PYTHON_DIR%\Lib\distutils\distutils.cfg
    - patch %PYTHON_DIR%\lib\distutils\cygwinccompiler.py platform\patch.diff
    - copy %PYTHON_DIR%\vcruntime140.dll %PYTHON_DIR%\libs

    # Install modules.
    - pip install -r requirements.txt

    # Show tool kits.
    - gcc --version
    - mingw32-make --version

build_script:
    - mingw32-make

test_script:
    - mingw32-make test
